 $creds = Get-Credential a-breasor@remyusa.com
Invoke-RestMethod -Uri "https://outlook.office365.com/api/v1.0/users/judd.zusel@remyusa.com/contacts?`$top=500" -Credential $creds | foreach-object{ $_.Value } | 
#Invoke-RestMethod -Uri "https://outlook.office365.com/api/v1.0/me/contacts" -Credential $creds | foreach-object{ $_.Value } | 
    Select-Object Title, 
                  @{Name="First Name";expression={$_.GivenName}},
                  @{Name="Middle Name";expression={$_.MiddleName}},
                  @{Name="Last Name";expression={$_.SurName}},
                  Suffix,
                  Company,
                  Department,
                  @{Name="Job Title";expression={$_.JobTitle}},
                  @{Name="Business Street";Expression={($_.BusinessAddress).Street}},
                  @{Name="Business City";Expression={($_.BusinessAddress).City}},
                  @{Name="Business State";Expression={($_.BusinessAddress).State}},
                  @{Name="Business Postal Code";Expression={($_.BusinessAddress).PostalCode}},
                  @{Name="Business Country/Region";Expression={($_.BusinessAddress).CountryOrRegion}},
                  @{Name="Home Street";Expression={($_.HomeAddress).Street}},
                  @{Name="Home City";Expression={($_.HomeAddress).City}},
                  @{Name="Home State";Expression={($_.HomeAddress).State}},
                  @{Name="Home Postal Code";Expression={($_.HomeAddress).PostalCode}},
                  @{Name="Home Country/Region";Expression={($_.HomeAddress).CountryOrRegion}},
                  @{Name="Business Phone";Expression={(($_.BusinessPhones)[0])}},
                  @{Name="Business Phone 2";Expression={(($_.BusinessPhones)[1])}},
                  @{Name="Email Address 1";Expression={(($_.EmailAddresses)[0]).Address}},
                  @{Name="Email Display Name 1";Expression={(($_.EmailAddresses)[0]).Name}},
                  @{Name="Email Address 2";Expression={(($_.EmailAddresses)[1]).Address}},
                  @{Name="Email Display Name 2";Expression={(($_.EmailAddresses)[1]).Name}},
                  @{Name="Email Address 3";Expression={(($_.EmailAddresses)[2]).Address}},
                  @{Name="Email Display Name 3";Expression={(($_.EmailAddresses)[2]).Name}},
                  @{Name="Home Phone";Expression={(($_.HomePhones)[0])}},
                  @{Name="Home Phone 2";Expression={(($_.HomePhones)[1])}},
                  MobilePHone1, 
                  Notes,
                  Birthday | Export-Csv -NoTypeInformation C:\temp\judd-contacts.csv 